name: Setup SQLite Database

on:
  workflow_dispatch:

jobs:
  setup-db:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"
    - name: Install Dependencies
      run: npm install
    - name: Generate DB
      run: npm run gen:db
    - name: Commit Changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "action@github.com"
        git add ./src/data/data.db
        git commit -m "Update tiles via GitHub Actions" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}